site_name: ARM mbed Web Application Example
theme: readthedocs
use directory_urls: false
pages:
- ['index.md','ARM mbed Web Application']
- ['README.md','Quick guide to the example application','mbed Web Application']





